name: notes_app
description: A note taking application.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.18.0 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_analytics: ^9.3.8
  cloud_firestore: ^3.5.1
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets: []
  fonts: []
